cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'ack'
brew 'tig'
brew 'readline'
brew 'git-extras'
brew 'spaceman-diff'
brew 'the_silver_searcher'
brew 'ansiweather'

#brew 'ansible'
#brew 'coreutils'
#brew 'fasd'
#brew 'go'
#brew 'grc'
#brew 'imagemagick'
#brew 'jp2a'
#brew 'libcaca', args: ['with-imlib2']
#brew 'libgit2'
#brew 'mongodb'
#brew 'openssl'
#brew 'node'
#brew 'postgresql'
#brew 'ruby-build'
#brew 'rbenv'
#brew 'roundup'
#brew 'spark'
#brew 'unrar'
#brew 'wget'
#brew 'youtube-dl'



cask 'skitch'
cask 'evernote'
cask 'firefox'
cask 'google-chrome'
cask 'slack'

#cask '1password'
#cask 'atom'
#cask 'caffeine'
#cask 'dropbox'
#cask 'handbrake'
#cask 'moom'
#cask 'private-internet-access'
#cask 'sketchup'
#cask 'spotify'
#cask 'steam'
#cask 'transmission'
#cask 'vlc'
#cask 'seil'
#cask 'skype'
